### ISSUE TITLE
Error by building

### ISSUE THREAD

**Issue by melihyazgan** [ms-van3t-devs/ms-van3t#13]
Greetings,

i am getting following errors:
fatal error: ns3/v2xEmulator.h: No such file or directory
   24 | #include "ns3/v2xEmulator.h"
   ns3/simpleCAMSender-gps-tc.h: No such file or directory
    3 | #include "ns3/simpleCAMSender-gps-tc.h"
    ns3/areaSpeedAdvisorServer80211p.h: No such file or directory
   24 | #include "ns3/areaSpeedAdvisorServer80211p.h"
   
   I followed the readme. OpenCda and Carla are working but I can't build ms-van3t. Do you guys have an idea maybe?
   
   Regards,
   Melih

**Comment by melihyazgan** [comment]
Another question regarding the process after build
Is there any example config file? Because the examples expect the "ms_van3t_example.yaml" file but it is not provided

**Comment by melihyazgan** [comment]
Hi Carlos,
thank you, somehow it was broken by me. I am getting the following error after I switch the caarla and try to build
![Screenshot from 2024-02-05 16-45-39](https://github.com/ms-van3t-devs/ms-van3t/assets/15940617/030474fb-59aa-4762-898a-692f78647cd4)

**Comment by carlosrisma** [comment]
Hi Melih,

the error you were getting was due to an incompatibility of the ms-van3t-CARLA CMakeLists.txt. Now we have updated the CARLA extension auxiliary files and the error should disappear. You should pull from the last commit and run the _./switch_ms-van3t-CARLA.sh_ script twice.

Cheers,
Carlos

**Comment by melihyazgan** [comment]
Hi Carlos,
Thank you for your help and updates.
I removed the old repo and started from scratch. But this time I am getting following error, which I couldnÄt understand the issue. Because Cmakefile seems correct to me. The errors are following

[  0%] Building CXX object src/automotive/CMakeFiles/libautomotive-obj.dir/helper/trafficManagerClient80211p-helper.cc.o
/home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/src/automotive/helper/v2xEmulator-helper.cc:24:10: fatal error: ns3/v2xEmulator.h: No such file or directory
   24 | #include "ns3/v2xEmulator.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/automotive/CMakeFiles/libautomotive-obj.dir/build.make:146: src/automotive/CMakeFiles/libautomotive-obj.dir/helper/v2xEmulator-helper.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/src/automotive/helper/simpleCAMSender-helper.cc:3:10: fatal error: ns3/simpleCAMSender-gps-tc.h: No such file or directory
    3 | #include "ns3/simpleCAMSender-gps-tc.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/automotive/CMakeFiles/libautomotive-obj.dir/build.make:160: src/automotive/CMakeFiles/libautomotive-obj.dir/helper/simpleCAMSender-helper.cc.o] Error 1
[  0%] Linking CXX shared library /home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/build/lib/libns3-dev-wave-optimized.so
[  0%] Linking CXX shared library /home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/build/lib/libns3-dev-lte-optimized.so
[  0%] Linking CXX shared library /home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/build/lib/libns3-dev-cv2x-optimized.so
[  0%] Building CXX object src/bridge/examples/CMakeFiles/csma-bridge.dir/csma-bridge.cc.o
[  0%] Linking CXX executable /home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/build/src/bridge/examples/ns3-dev-csma-bridge-optimized
/home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/src/automotive/helper/areaSpeedAdvisorClient80211p-helper.cc:24:10: fatal error: ns3/areaSpeedAdvisorClient80211p.h: No such file or directory
   24 | #include "ns3/areaSpeedAdvisorClient80211p.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/automotive/CMakeFiles/libautomotive-obj.dir/build.make:76: src/automotive/CMakeFiles/libautomotive-obj.dir/helper/areaSpeedAdvisorClient80211p-helper.cc.o] Error 1
[  1%] Building CXX object src/bridge/examples/CMakeFiles/csma-bridge-one-hop.dir/csma-bridge-one-hop.cc.o
[  1%] Linking CXX executable /home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/build/src/bridge/examples/ns3-dev-csma-bridge-one-hop-optimized
/home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/src/automotive/helper/areaSpeedAdvisorServerLTE-helper.cc:24:10: fatal error: ns3/areaSpeedAdvisorServerLTE.h: No such file or directory
   24 | #include "ns3/areaSpeedAdvisorServerLTE.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/automotive/CMakeFiles/libautomotive-obj.dir/build.make:118: src/automotive/CMakeFiles/libautomotive-obj.dir/helper/areaSpeedAdvisorServerLTE-helper.cc.o] Error 1
/home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/src/automotive/helper/areaSpeedAdvisorClientLTE-helper.cc:24:10: fatal error: ns3/areaSpeedAdvisorClientLTE.h: No such file or directory
   24 | #include "ns3/areaSpeedAdvisorClientLTE.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/src/automotive/helper/areaSpeedAdvisorServer80211p-helper.cc:24:10: fatal error: ns3/areaSpeedAdvisorServer80211p.h: No such file or directory
   24 | #include "ns3/areaSpeedAdvisorServer80211p.h"


Cheers,
Melih

**Comment by valerionori** [comment]
Hi,

maybe I can help you since I faced a similar issue.

Basically the error tells you that you should use the `--apply_ml `argument, meaning using PyTorch to achieve the perception of other vehicles.

In that specific example this should not happen, however it occurs because the developers probably modified the code later on.

Go to `OpenCDA/opencda/scenario_testing/config_yaml`. You will see the `.yaml` files of every example.
In the `.yaml` file of your specific example, you may note the lines:

```
perception
  activate: true
```

This means that the script will use PyTorch for detecting vehicles, thus forcing you to add the above mentioned attribute. Set `activate: false` to retrieve vehicle position by the server and the error should disappear.

Moreover, note that the `.yaml` configuration are a merge between the `.yaml` file of your example and the `default.yaml` file.
So, when some attribute is not mentioned you should look at `default.yaml` to see how it is set.

**Comment by melihyazgan** [comment]
Hi Valeri,
thank you for your help. I noticed that after I tried ml examples given in OpenCDA Documentation. The ml scenarios are working but the others like platoon_stability_2lanefree_carla still not. I did add the activate attribute and assigned it as false. I am getting another error regarding initial positions.
python opencda.py -t platoon_joining_2lanefree_carla -v 0.9.12
OpenCDA Version: 0.1.3
load opendrive map '2lane_freeway_simplified.xodr'.
Creating platoons/
Traceback (most recent call last):
  File "/home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/OpenCDA/opencda/scenario_testing/platoon_joining_2lanefree_carla.py", line 42, in run_scenario
    data_dump=False)
  File "/home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/OpenCDA/opencda/scenario_testing/utils/sim_api.py", line 536, in create_platoon_manager
    data_dumping=data_dump)
  File "/home/nj644/dev/v2x-sim/ms-van3t/ns-3-dev/OpenCDA/opencda/customize/core/common/vehicle_manager.py", line 147, in __init__
    if config_yaml['v2x']['platoon_init_pos'] == 1:
  File "/home/nj644/dev/anaconda3/envs/msvan3t_carla/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/nj644/dev/anaconda3/envs/msvan3t_carla/lib/python3.7/site-packages/omegaconf/base.py", line 237, in _format_and_raise
    type_override=type_override,
  File "/home/nj644/dev/anaconda3/envs/msvan3t_carla/lib/python3.7/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/nj644/dev/anaconda3/envs/msvan3t_carla/lib/python3.7/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/nj644/dev/anaconda3/envs/msvan3t_carla/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/nj644/dev/anaconda3/envs/msvan3t_carla/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 443, in _get_impl
    key=key, throw_on_missing_key=True, validate_key=validate_key
  File "/home/nj644/dev/anaconda3/envs/msvan3t_carla/lib/python3.7/site-packages/omegaconf/basecontainer.py", line 78, in _get_child
    throw_on_missing_key=throw_on_missing_key,
  File "/home/nj644/dev/anaconda3/envs/msvan3t_carla/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigKeyError: Missing key platoon_init_pos
    full_key: vehicle_base.v2x.platoon_init_pos
    object_type=dict

**Comment by valerionori** [comment]
I am aware of that error too and actually I do not know how to solve it.

I tried to install the standard OpenCDA (not the fork created for ms_van3t) and platoon examples work as well.

Maybe the error could be due to omegaconf version, but I am not sure.
You may try to install omegaconf 2.3.0 (`pip install omegaconf==2.3.0`), but I don't know actually if it will mess up anything and solve the error.

I will try in these days to found a correct solution.

**Comment by valerionori** [comment]
Hi,

Unfortunately I put aside the CARLA integration at the moment.
Right now I'm focusing on introducing Redundancy Mitigation Techniques for the Cooperative Perception Service (relying on SUMO instead of CARLA).

Best regards,

Valerio

**Comment by carlosrisma** [comment]
Hi all, 
apologies for the delay in the reply. 
About the platoon_stability_2lanefree_carla example for OpenCDA scenarios, the issue is due to an incompatibility between the ms-van3t fork and the base OpenCDA framework. We are currently working on adding a Platooning facilities layer protocol implementation for ms-van3t, to then support platooning scenarios in co-simulation.
For now, the only scenario that has been fully tested for co-simulation is indeed the ms_van3t_example and the others should be considered as leftovers that we will now delete from the repository to avoid misunderstandings. 

Best regards,
Carlos

**Comment by carlosrisma** [comment]
Hi Melih,

   thank you very much for the detailed bug report. With the debug trace, I was able to spot the issue and it should be solved with the latest commit. Thanks a lot! 

Carlos

**Comment by melihyazgan** [comment]
Hi Carlos,
thank you! The examples are working right now
