### ISSUE TITLE
Linking failed

### ISSUE THREAD

**Issue by NAGISAZHANG** [ms-van3t-devs/ms-van3t#43]
Hi Carlos,
I encountered an issue when setting up a hybrid LTE and WiFi network in my project. Specifically, SIP is my custom script located in the scratch directory. I received the following error during execution, :
"Linking CXX executable ../build/scratch/ns3-dev-SIP-default
assert failed. cond="m_namemap.count (name) == 0", msg="Trying to allocate twice the same uid: ns3::RssiTag", file=../src/core/model/type-id.cc, line=387
terminate called without an active exception
Command 'build/scratch/ns3-dev-SIP-default' died with <Signals.SIGABRT: 6>."
Do you have any ideas or suggestions on what might be causing this issue?
Best regards,
NAGISA

**Comment by francescoraves483** [comment]
Dear Nagisa,
Thank you for reporting the issue!

The issue seems to be related to the fact that you are using multiple technologies at the same time (LTE + IEEE 802.11p), and each of them has (in their internal implementation) an RSSI tag with the same ns-3 type ID "ns3::RssiTag". RSSI tags are special objects that are attached to packets and used to report signal information (like RSSI, RSRP, ...) to the application layer. When using a single technlogy, the issue is not occurring as there is a single RSSI tag involved, but when multiple technologies are used, apparently ns-3 does not like the fact that the RSSI tags for Wi-Fi and LTE are associated to the same type ID.

We are currently working on the issue, trying to create different RSSI tags, with different type IDs, for each technology and a wrapper class that makes it transparent to the user which kind of RSSI tag has been used. However, this requires a bit of time and some non-trivial updates to the code. We will get back to you as soon as we are able to fix the bug!

For the time being, the quickest solution would be to stick with simulations that rely on a single technlogy at a time (for example by using RSUs instead of LTE for communicating with the infrastructure).

Thank you!
Best,
Francesco

**Comment by NAGISAZHANG** [comment]
Dear Francesco,

Thank you very much for your detailed explanation and prompt response. I now have a clearer understanding of the cause of the issue. 

Thanks again for you!

Best regards,
Nagisa
